[package]
name = "dc-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
poise = "0.5.0"
tokio = { version = "1.4.0", features = ["rt-multi-thread", "process"] }
base64 = "0.13.0"
rsa = "0.7.2"
sha3 = "0.10.6"